-- AMV Vocal Intelligence v1
-- Ejecutar en Supabase después de revisar nombres/roles del proyecto.

create table if not exists public.vocal_recordings (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students(id) on delete cascade,
  title text not null default 'Grabación vocal',
  song text not null default '',
  storage_path text not null,
  audio_url text,
  duration_seconds integer,
  recorded_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.vocal_ai_analyses (
  id bigint generated by default as identity primary key,
  recording_id bigint not null references public.vocal_recordings(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','processing','completed','failed')),
  model text not null default '',
  summary text not null default '',
  strengths jsonb not null default '[]'::jsonb,
  priorities jsonb not null default '[]'::jsonb,
  dimensions jsonb not null default '{}'::jsonb,
  limitations jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(recording_id)
);

create index if not exists vocal_recordings_student_date_idx
  on public.vocal_recordings(student_id, recorded_at desc);

alter table public.vocal_recordings enable row level security;
alter table public.vocal_ai_analyses enable row level security;

-- Lectura: profesor o el propio estudiante vinculado.
create policy "vocal_recordings_select_teacher_or_owner"
on public.vocal_recordings for select to authenticated
using (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'teacher')
  or exists (select 1 from public.profiles p where p.id = auth.uid() and p.student_id = vocal_recordings.student_id)
);

create policy "vocal_recordings_teacher_write"
on public.vocal_recordings for all to authenticated
using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'teacher'))
with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'teacher'));

create policy "vocal_ai_analyses_select_teacher_or_owner"
on public.vocal_ai_analyses for select to authenticated
using (
  exists (
    select 1 from public.vocal_recordings vr
    join public.profiles p on p.student_id = vr.student_id
    where vr.id = vocal_ai_analyses.recording_id
      and (p.id = auth.uid() or exists (select 1 from public.profiles t where t.id = auth.uid() and t.role='teacher'))
  )
);

-- INSERT/UPDATE de análisis NO se concede al cliente.
-- Debe ejecutarlo una Edge Function segura con service role después de autorizar al profesor.

-- Storage recomendado:
-- bucket privado: vocal-recordings
-- policies: teacher insert/delete; teacher + owner select.
