-- =========================================================
-- AMV · VOCAL INTELLIGENCE V1
-- Academia de Talentos Amo Mi Voz
-- =========================================================


-- =========================================================
-- 1. TABLA DE GRABACIONES VOCALES
-- =========================================================

create table if not exists public.vocal_recordings (
  id bigint generated by default as identity primary key,

  student_id bigint not null
    references public.students(id)
    on delete cascade,

  title text not null
    default 'Grabación vocal',

  song text not null
    default '',

  storage_path text not null,

  audio_url text,

  duration_seconds integer,

  recorded_at timestamptz not null
    default now(),

  created_at timestamptz not null
    default now(),

  updated_at timestamptz not null
    default now()
);


-- =========================================================
-- 2. TABLA DE ANÁLISIS DE IA
-- =========================================================

create table if not exists public.vocal_ai_analyses (
  id bigint generated by default as identity primary key,

  recording_id bigint not null
    references public.vocal_recordings(id)
    on delete cascade,

  status text not null
    default 'pending'

    check (
      status in (
        'pending',
        'processing',
        'completed',
        'failed'
      )
    ),

  model text not null
    default '',

  summary text not null
    default '',

  strengths jsonb not null
    default '[]'::jsonb,

  priorities jsonb not null
    default '[]'::jsonb,

  dimensions jsonb not null
    default '{}'::jsonb,

  limitations jsonb not null
    default '[]'::jsonb,

  created_at timestamptz not null
    default now(),

  updated_at timestamptz not null
    default now(),

  unique(recording_id)
);


-- =========================================================
-- 3. ÍNDICES
-- =========================================================

create index if not exists
  vocal_recordings_student_date_idx

on public.vocal_recordings (
  student_id,
  recorded_at desc
);


create index if not exists
  vocal_ai_analyses_recording_idx

on public.vocal_ai_analyses (
  recording_id
);


-- =========================================================
-- 4. PERMISOS SQL
-- =========================================================
--
-- IMPORTANTE:
--
-- Crear una tabla desde SQL Editor no garantiza que el rol
-- authenticated tenga los privilegios necesarios.
--
-- Estas instrucciones solucionan:
--
-- "permission denied for table vocal_recordings"
--
-- =========================================================

grant select, insert, update, delete
on table public.vocal_recordings
to authenticated;


grant select
on table public.vocal_ai_analyses
to authenticated;


-- Permisos sobre las secuencias de IDENTITY

grant usage, select
on sequence public.vocal_recordings_id_seq
to authenticated;


grant usage, select
on sequence public.vocal_ai_analyses_id_seq
to authenticated;


-- =========================================================
-- 5. ROW LEVEL SECURITY
-- =========================================================

alter table public.vocal_recordings
enable row level security;


alter table public.vocal_ai_analyses
enable row level security;


-- =========================================================
-- 6. POLÍTICA DE LECTURA DE GRABACIONES
-- =========================================================

drop policy if exists
  "vocal_recordings_select_teacher_or_owner"

on public.vocal_recordings;


create policy
  "vocal_recordings_select_teacher_or_owner"

on public.vocal_recordings

for select

to authenticated

using (

  -- Profesor
  exists (
    select 1

    from public.profiles p

    where
      p.id = auth.uid()
      and p.role = 'teacher'
  )

  OR

  -- Propio estudiante
  exists (
    select 1

    from public.profiles p

    where
      p.id = auth.uid()
      and p.student_id = vocal_recordings.student_id
  )

);


-- =========================================================
-- 7. POLÍTICA DE ESCRITURA DE GRABACIONES
-- =========================================================
--
-- Actualmente solamente el profesor puede crear,
-- modificar o eliminar grabaciones.
--
-- =========================================================

drop policy if exists
  "vocal_recordings_teacher_write"

on public.vocal_recordings;


create policy
  "vocal_recordings_teacher_write"

on public.vocal_recordings

for all

to authenticated

using (

  exists (
    select 1

    from public.profiles p

    where
      p.id = auth.uid()
      and p.role = 'teacher'
  )

)

with check (

  exists (
    select 1

    from public.profiles p

    where
      p.id = auth.uid()
      and p.role = 'teacher'
  )

);


-- =========================================================
-- 8. LECTURA DE ANÁLISIS DE IA
-- =========================================================

drop policy if exists
  "vocal_ai_analyses_select_teacher_or_owner"

on public.vocal_ai_analyses;


create policy
  "vocal_ai_analyses_select_teacher_or_owner"

on public.vocal_ai_analyses

for select

to authenticated

using (

  exists (

    select 1

    from public.vocal_recordings vr

    join public.profiles p
      on p.student_id = vr.student_id

    where
      vr.id = vocal_ai_analyses.recording_id

      and (

        -- Alumno propietario
        p.id = auth.uid()

        OR

        -- Profesor
        exists (
          select 1

          from public.profiles teacher_profile

          where
            teacher_profile.id = auth.uid()
            and teacher_profile.role = 'teacher'
        )

      )

  )

);


-- =========================================================
-- 9. STORAGE BUCKET
-- =========================================================

insert into storage.buckets (
  id,
  name,
  public
)

values (
  'vocal-recordings',
  'vocal-recordings',
  false
)

on conflict (id)

do update set
  public = false;


-- =========================================================
-- 10. STORAGE · LECTURA
-- =========================================================

drop policy if exists
  "vocal_recordings_storage_select"

on storage.objects;


create policy
  "vocal_recordings_storage_select"

on storage.objects

for select

to authenticated

using (

  bucket_id = 'vocal-recordings'

  AND

  (

    -- Profesor
    exists (
      select 1

      from public.profiles p

      where
        p.id = auth.uid()
        and p.role = 'teacher'
    )

    OR

    -- Alumno propietario
    exists (
      select 1

      from public.profiles p

      where
        p.id = auth.uid()

        and

        p.student_id::text =
          split_part(name, '/', 1)
    )

  )

);


-- =========================================================
-- 11. STORAGE · SUBIDA
-- =========================================================

drop policy if exists
  "vocal_recordings_storage_insert"

on storage.objects;


create policy
  "vocal_recordings_storage_insert"

on storage.objects

for insert

to authenticated

with check (

  bucket_id = 'vocal-recordings'

  AND

  exists (
    select 1

    from public.profiles p

    where
      p.id = auth.uid()
      and p.role = 'teacher'
  )

);


-- =========================================================
-- 12. STORAGE · ELIMINACIÓN
-- =========================================================

drop policy if exists
  "vocal_recordings_storage_delete"

on storage.objects;


create policy
  "vocal_recordings_storage_delete"

on storage.objects

for delete

to authenticated

using (

  bucket_id = 'vocal-recordings'

  AND

  exists (
    select 1

    from public.profiles p

    where
      p.id = auth.uid()
      and p.role = 'teacher'
  )

);


-- =========================================================
-- FIN AMV VOCAL INTELLIGENCE V1
-- =========================================================